### ISSUE TITLE
Could you give some instruction how to use your library

### ISSUE THREAD

**Issue by WangZilu0218** [ZakayZ/FermiBreakUp#1]
I am really interest your atomic break up library, could you give some examples to show how calculate two atomic collision?thank you!

**Comment by ZakayZ** [comment]
This code is suppose to be a part of a bigger library (https://github.com/Spectator-matter-group-INR-RAS/AAMCC). It is similar to Fermi Break Up in Geant4, and as such is not designed to calculate atomic collision, just decay of highly energetic particles. I am probably going to add documentation in the future, however some simple use cases may be found in tests right now.
