### ISSUE TITLE
Build fails due to [unlikely] attribute

### ISSUE THREAD

**Issue by apBUSampK** [ZakayZ/FermiBreakUp#4]
Screenshot attached:

![image](https://github.com/user-attachments/assets/8986be5f-f5ca-4b41-ba1e-27575d920123)

**Comment by apBUSampK** [comment]
Compiled via
```ssh
$ cmake /../FermiBreakUp/COLA
$ cmake --build ./ --target install
```

**Comment by ZakayZ** [comment]
Должно теперь выполнятся только при сборке с >=c++20
